<?php
// $Id$

/**
 * Implementation of hook_uninstall().
 */
function site_map_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'site_map_%'");
}

/**
 * Delete no longer used variables.
 */
function site_map_update_6000() {
  $ret = array();
  $ret[] = update_sql("DELETE FROM {variable} WHERE name LIKE 'site_map_message_%'");
  $ret[] = update_sql("DELETE FROM {variable} WHERE name LIKE 'site_map_show_menus_%'");
  return $ret;
}
