# Schema for the configuration files of the Site Map module.

site_map.settings:
  type: config_object
  label: 'Site map settings'
  mapping:
    page_title:
      type: string
      label: 'Page title'
    message:
      type: text_format
      label: 'Site map message'
    show_front:
      type: boolean
      label: 'Show front flag'
    show_titles:
      type: boolean
      label: 'Show titles flag'
    show_blogs:
      type: boolean
      label: 'Show active blog authors flag'
    show_books:
      type: sequence
      label: 'Books to display'
      sequence:
        - type: integer
          label: 'Book id'
    books_expanded:
      type: boolean
      label: 'Books expanded flag'
    show_menus:
      type: sequence
      label: 'Menus to display'
      sequence:
        - type: string
          label: 'Menu id'
    show_menus_hidden:
      type: boolean
      label: 'Show disabled menu items flag'
    show_faq:
      type: boolean
      label: 'Show FAQ flag'
    show_vocabularies:
      type: sequence
      label: 'Vocabularies to display'
      sequence:
        - type: string
          label: 'Vocabulary id'
    show_description:
      type: boolean
      label: 'Show vocabulary description flag'
    show_count:
      type: boolean
      label: 'Show node count by taxonomy term flag'
    vocabulary_depth:
      type: integer
      label: 'Vocabulary depth'
    term_threshold:
      type: integer
      label: 'Term count threshold'
    forum_threshold:
      type: integer
      label: 'Forum count threshold'
    rss_front:
      type: string
      label: 'RSS front'
    show_rss_links:
      type: integer
      label: 'Position of RSS links'
    rss_taxonomy:
      type: integer
      label: 'RSS depth'
    css:
      type: boolean
      label: 'Exclude css file flag'
    order:
      type: sequence
      label: 'Site map order'
      sequence:
        - type: site_map.order.[%key]

site_map.order.*:
  type: integer
  label: 'Weight'
